version: '3.7'
services:
  app:
    container_name: 'app'
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    networks:
      - ${NETWORK}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      PORT: ${PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  postgres:
    container_name: 'postgres'
    build: ./database/
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - ${NETWORK}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
networks:
  home-library-network:
    driver: bridge
    name: ${NETWORK}
volumes:
  app:
  db-data: