version: '3.7'
services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    networks:
      - ${NETWORK}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      PORT: ${PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  postgres:
    build: ./database/
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - ${NETWORK}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ['postgres', '-c', 'log_statement=all', '-c', 'logging_collector=on']
networks:
  home-library-network:
    driver: bridge
    name: ${NETWORK}
    ipam:
      driver: default
      config:
        - subnet: '192.168.0.0/24'
          gateway: '192.168.0.1'