version: '3.7'
services:
  app:
    container_name: 'app'
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      PORT: ${PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  postgres:
    container_name: 'postgres'
    build: ./database/
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
