version: '3.8'
services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: /src
          target: /user/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    networks:
      - ${NETWORK}
    env_file:
      - .env
  db:
    build: ./database/
    container_name: postgres
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - ${NETWORK}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ['postgres', '-c', 'log_statement=all', '-c', 'logging_collector=on']
networks:
  home-library-network:
    driver: ${DRIVER}
    name: ${NETWORK}
    ipam:
      driver: default
      config:
        - subnet: '192.168.0.0/24'
          gateway: '192.168.0.1'
volumes:
  db-data:
    driver: local